name: Meu primeiro workflow no Github Action

on:
  push:
    branches: [ "main" ]

jobs:
  test_job:
    name: Executando o job de teste
    runs-on: self-hosted
    steps:
      - name: Step 1
        uses: actions/checkout@v4

      - name: Step 2
        run: echo Olá mundo!
